service: default
runtime: php55
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /(.*)
    static_files: elm.js
    upload: elm.js

  - url: /assets
    static_dir: assets

  - url: /.*
    script: auto
