steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['ci']
  - name: 'node'
    entrypoint: 'npm'
    args: ['build']
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
